insert into `genres` (`genreId`, `name`) values('1','Action');
insert into `genres` (`genreId`, `name`) values('2','Adventure');
insert into `genres` (`genreId`, `name`) values('3','Comedy');
insert into `genres` (`genreId`, `name`) values('4','Demons');
insert into `genres` (`genreId`, `name`) values('5','Drama');
insert into `genres` (`genreId`, `name`) values('6','Ecchi');
insert into `genres` (`genreId`, `name`) values('7','Fantasy');
insert into `genres` (`genreId`, `name`) values('8','Game');
insert into `genres` (`genreId`, `name`) values('9','Harem');
insert into `genres` (`genreId`, `name`) values('10','Historical');
insert into `genres` (`genreId`, `name`) values('11','Horror');
insert into `genres` (`genreId`, `name`) values('12','Josei');
insert into `genres` (`genreId`, `name`) values('13','Magic');
insert into `genres` (`genreId`, `name`) values('14','Martial Arts');
insert into `genres` (`genreId`, `name`) values('15','Mecha');
insert into `genres` (`genreId`, `name`) values('16','Military');
insert into `genres` (`genreId`, `name`) values('17','Music');
insert into `genres` (`genreId`, `name`) values('18','Mystery');
insert into `genres` (`genreId`, `name`) values('19','Psychological');
insert into `genres` (`genreId`, `name`) values('20','Parody');
insert into `genres` (`genreId`, `name`) values('21','Police');
insert into `genres` (`genreId`, `name`) values('22','Romance');
insert into `genres` (`genreId`, `name`) values('23','Samurai');
insert into `genres` (`genreId`, `name`) values('24','School');
insert into `genres` (`genreId`, `name`) values('25','Sci-Fi');
insert into `genres` (`genreId`, `name`) values('26','Seinen');
insert into `genres` (`genreId`, `name`) values('27','Shoujo');
insert into `genres` (`genreId`, `name`) values('28','Shoujo Ai');
insert into `genres` (`genreId`, `name`) values('29','Shounen');
insert into `genres` (`genreId`, `name`) values('30','Slice of Life');
insert into `genres` (`genreId`, `name`) values('31','Sports');
insert into `genres` (`genreId`, `name`) values('32','Space');
insert into `genres` (`genreId`, `name`) values('33','Super Power');
insert into `genres` (`genreId`, `name`) values('34','Supernatural');
insert into `genres` (`genreId`, `name`) values('35','Thriller');
insert into `genres` (`genreId`, `name`) values('36','Vampire');
